steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - '${_CLUSTER_NAME}'
    - '--zone'
    - '${_CLUSTER_ZONE}'
    - '--project'
    - '${_PROJECT_ID}'
  id: 'Get GKE Credentials'

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/viks1102/gke-deployments.git']
  dir: '/workspace'
  id: 'Clone Repo'

# Apply deployment manifests
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - '/workspace/gke-deployments/nonprod/'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  id: 'Apply constrainttemplate'

# Step 6: Get all pods
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'pods', '-o', 'wide']
  id: 'Get Pods'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _CLUSTER_NAME: 'gke-cluster-nonprod'
  _CLUSTER_ZONE: 'us-central1-b'
  _PROJECT_ID: 'dtonic-demo-k8s'
